### ISSUE TITLE
Doplněk přestal fungovat

### ISSUE THREAD

**Issue by ToKroCZ** [kodi-czsk/plugin.video.dmd-czech.prima#2]
Po pokusu o přehrání jakéhokoliv videa z archivu Primy se objeví hláška "chyba skriptu". Kodi 14.2 Helix, Ubuntu. Do teď funkční.

**Comment by lgreg** [comment]
Tohle uz asi funguje a muzu uzavrit ne?

**Comment by ToKroCZ** [comment]
Ano
