### ISSUE TITLE
Nejsou splneny zavislosti

### ISSUE THREAD

**Issue by Milan71** [kodi-czsk/plugin.video.dmd-czech.prima#6]
PLS o aktualizaci v KODI 15.1 nejde bohuzel spustit... :-(

Dekuji

**Comment by lgreg** [comment]
Zkousel jsem na 14.2 a 15.2 a na obou funguje bez problemu. Bud zkuste updatovat na 15.2 a pokud to nepomuze vlozte prosim log, takhle netusim jaka zavislost neni splnena a nejsem schopny pripadny problem opravit...

**Comment by Milan71** [comment]
Dobry vecer, dekuji za rychlou odpoved.

Mam rapsberry pi2 kratce, omlouvam se za neznalost, jak se da vytvorit/poslat log?

Zkusim upgrade na 15.2, ale myslim, ze vcera jeste nebyl dostupny...

```
M.V:
```

**Comment by lgreg** [comment]
Nemam u sebe ted raspberry, ale zkuste to podle tohoto navodu - http://kodi.wiki/view/Log_file/Easy
Kdyz to nepomuze, tak pohledejte log, jak z Vaseho systemu log dostat.

**Comment by Milan71** [comment]
Ted jsem na to koukal, mam KODI 14.2 Git 7cc53a9 Compiled MAr 31 2015...

Pak by to melo byt vse OK, ale bohuzel neni... :-(

**Comment by Milan71** [comment]
OK, vytvorim log dle navodu, pls o adresu, kam Vam ho mam poslat. Dekuji

**Comment by lgreg** [comment]
14.2 by mel byt v pohode, v nem sem to testoval i ja a plugin normalne bezi.
Log prosim nahrajte pres http://pastebin.com/ a dejte sem odkaz, diky.

**Comment by Milan71** [comment]
Log je k dispozici zde: http://xbmclogs.com/p4ied7h78

Pokusim se ho i nahrat...
Log je obrovsky a to jsem jen zkusil nainstalovat doplnek a pak hned vypnul logovani...

Stacil by pls jen ten odkaz?

**Comment by lgreg** [comment]
Ten odkaz staci. Koukam na to a jediny co jsem nasel je chybejici zavislost na baliku script.module.dmd-czech.common, kterej je ale spravne soucasti repozitare. Tudiz nechapu, pokud jste doplnek pro Primu instaloval z repozitare Kodi CZ/SK doplnku (instalace popsana zde - http://kodi-czsk.github.io/repository/), tak se spravne musi insgtalovat i balik ze zavislosti. Mozna bych zkusil odinstalovat a znovu nainstalovat doplnek pro primu, pokud to nepomuze, tak zkuste sem hodit na vas nejakej kontakt a muzem to jeste probrat, at to tady naspamujem ;)

**Comment by lzoubek** [comment]
@lgreg zmenil jsem verzi zavislosti na 1.5.8 (coz je verze dmd-common, co je v tomto repu), prosim otestuj

**Comment by lgreg** [comment]
@lzoubek vecer zkusim cistou instalaci primy jestli se mi zavislost dotahne...

**Comment by lgreg** [comment]
@lzoubek nejde mi rozjet dalsi cista instalce kodi bez pluginu, vzdycky se mi tam dotahnou pluginy z jiz existujici instace kodi, nicmene kdyz koukam na tu zmenu, kterou si provedl, tak tam se nemuze nic rozbit, takze za me ok. At vyzkousi @Milan71 , jestli uz mu pujde plugin primy nainstalovat....

**Comment by lzoubek** [comment]
Reinstalace kodi nepomuze, musis vycistit profil (tipuju nekde v  
C:/Users/ApplicationData/Kodi)
On Mon, 26 Oct 2015 22:35:19 +0100, lgreg notifications@github.com wrote:

> @lzoubek nejde mi rozjet dalsi cista instalce kodi bez pluginu, vzdycky  
> se mi tam dotahnou pluginy z jiz existujici instace kodi, nicmene kdyz  
> koukam na tu zmenu, kterou si provedl, tak tam se nemuze nic rozbit,  
> takze za me ok. At vyzkousi @Milan71 , jestli uz mu pujde plugin primy  
> nainstalovat....
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kodi-czsk/plugin.video.dmd-czech.prima/issues/6#issuecomment-151291419

## 

Libor Zoubek

**Comment by lgreg** [comment]
J, v OS X je to trochu jinak, ale to je jedno :D smazal sem adresar Kodi, tim padem jsem mel cisty Kodi, naistaloval repozitar CZ/SK doplnku, povolil Primu a dotahl se i common, takze za me cajk :)

**Comment by Milan71** [comment]
Panove, MOC dekuji za pomoc, omlouvam se ze jsem nereagoval, ale nestiham...
Behem dneska vyzkousim a ozvu se.

Preji pohodovou a klidnou Stredu :-)

**Comment by Milan71** [comment]
Zaclo to chodit! SUPER! :-) DIKY!

Pouze kdyz pustim sledujuserialy, tak to hodi chyba skriptu.... 
JInak vse ostatni OK! :-D
